# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Jay's Virtual Home"
subtitle: "A place to chill on the web"
name: "Jay Ambadkar"
email: "ambadkarj123@gmail.com"
domain: "thatjammydodger.github.io"
url: "https://thatjammydodger.github.io/"
description: >- # this means to ignore newlines until "baseurl:"
  "Hi! Seems you've found my site and I hope you like it. Commiserations if not.
  Really it's just a place for me to hang out digitally and put some stuff I like on.
  Have a look around and let me know if you have any thoughts on stuff I've written :)"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: "BlesssedPear"
github_username:  "ThatJammyDodger"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true


minimal_mistakes_skin: "air"
locale: "en-GB"
logo: "/assets/images/J88x88.png"

comments:
  provider: "disqus"
  disqus:
    shortname: "thatjammydodger"

author:
  name: "Jay"
  avatar: "/assets/images/icon.png"
  bio: "Aspiring maths (and maybe CS) student. Applying for university while studying for my A levels, having finished with GCSEs. Out to explore."
  location: "Somewhere, UK, Near Mars"
  links:
    - label: "X (formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlesssedPear"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jay.ams_/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCSEe39hrg0JbrrFzXvuefrw"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ThatJammyDodger"
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:ambadkarj123@gmail.com"
      
footer:
  links:
    - label: "X (formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlesssedPear"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ThatJammyDodger"

timezone: Europe/London

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
